spring.application.name=prasthanam-tours-backend
spring.data.mongodb.uri=mongodb+srv://raghavsohani1995_db_user:CSSlnkZpcPhb9BnR@cluster0.ojn6lxo.mongodb.net/prasthanam_tours?retryWrites=true&w=majority&appName=Cluster0
server.port=8081

logging.level.org.mongodb.driver=INFO
logging.level.org.springframework.data.mongodb=INFO